config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 root "main#home"

 resources :recipes 
 resources :users 

 post '/follow/:id', to: 'users#follow'
 post '/unfollow/:id', to: 'users#unfollow'

 post '/like/:id', to: 'recipes#like'
 post '/unlike/:id', to: 'recipes#unlike'

 get '/search/:id', to: 'search#index'
 get '/about/', to: 'about#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/recipe.rb
class Recipe < ApplicationRecord
has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/recipe.png"
validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

belongs_to :user
validates_uniqueness_of :name
acts_as_likeable

def self.search(search)
  if search
    where('name LIKE ? OR description LIKE ?', "%#{search}%", "%#{search}%")
  else
    all
  end
end
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name, :bio, :industry, :location

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/chef.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :recipes

  acts_as_followable
  acts_as_follower
  acts_as_liker
  
  def self.search(search)
    if search
      where('first_name LIKE ? OR last_name LIKE ?', "%#{search}%", "%#{search}%")
    else
      all
    end
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def about
		render :about
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    before_action :setup_extra_devise_fields, if: :devise_controller?

  	def setup_extra_devise_fields
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :bio, :industry, :company, :location, :avatar])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :bio, :industry, :company, :location, :avatar])
  	# devise_parameter_sanitizer.permit(:profile?????, keys: [:first_name, :last_name])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	before_action :authenticate_user!, :except => [:home]



	def home		

		if user_signed_in?			
			@user = User.first(12)
			@recipes = current_user.recipes

			@followees = current_user.followees(User)
			@followers = current_user.followers(User)
	
			render :signed_in_home
		else
			render :home
		end
		end

	

end










	# def user_profile
	# 	@the_user = User.find(params[:id])
	# 		# @user = User.id
	# 	render :user_profile
	# end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

def new
	@recipe = Recipe.new
	render :new
	# @recipe.save
end

def create
	
	@recipe = current_user.recipes.new(recipe_params)
	if @recipe.save
		redirect_to user_path(current_user)
	else
		flash[:message] = "Sorry this name is already taken!"
		render :new
	end
end

def edit

	recipe_id = params[:id]
	@recipe = current_user.recipes.find(recipe_id)
	render :edit

end

def update

	recipe_id = params[:id]
	@recipe = current_user.recipes.find(recipe_id)

	if @recipe.update(recipe_params)
		redirect_to user_path(current_user)
	else
		render :edit
	end

end

def show

	recipe_id = params[:id].to_i
	@recipe = Recipe.find(recipe_id)
	render :show

end

def destroy

	recipe_id = params[:id]

	@recipe = current_user.recipes.find(recipe_id)

	@recipe.destroy

	redirect_to current_user

end

def like

	recipe_id = params[:id].to_i
	likee = Recipe.find(recipe_id)
	current_user.like!(likee)
	redirect_to(:back)

end

def unlike

	
	recipe_id = params[:id].to_i
	likee = Recipe.find(recipe_id)
	current_user.unlike!(likee)
	redirect_to(:back)

end


private

	def recipe_params
		params.require(:recipe).permit(:name, :description, :instructions, :avatar)
		# params[:time_entry][:hours]
	end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

def index
  @user = User.search(params[:search])
  @recipe = Recipe.search(params[:search])
end





end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
	
	@user = User.find(params[:id])
	@recipes = @user.recipes
	@followees = @user.followees(User)
	@followers = @user.followers(User)
	@liked_recipes = current_user.likees(Recipe)

	render :show
end

def follow

	follower = current_user
	followee = User.find(params[:id])
	follower.follow!(followee)
	redirect_to(:back)

end

def unfollow

	follower = current_user
	followee = User.find(params[:id])
	follower.unfollow!(followee)
	redirect_to(:back)
	
end




end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/about.html.erb
<body class="aboutpic">
<div class="container">
	<div class="row h1about">
		<center><h1>Our Mission</h1></center>
	</div>
	<div class="row row-about">
		<div class="col-sm-6">
			<img src="assets/1.jpg" class="img-thumbnail img-thumbnail-about" alt="Image">
		</div>
		<div class="col-sm-6">
			<!-- <div class="well well-inside-about text-center"> -->
				<div class="aboutfont">
				BARCHEF is here to help chefs, bartenders and the occasional culinary enthusiast share recipes amongst themselves. This social platform allows you to follow users and track the latest restaurant and bar trends.  Keep track of your favorite recipes by liking them and share some of your own.  Sign up today!</div><p>
				<center><%= link_to "SIGN-UP", new_user_registration_path, class: "btn btn-default btn-home" %></center>
			<!-- </div> -->
		</div>
	</div>
</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Barchef</title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Cuprum" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
  </head>
  <body>
    <nav class="navbar menu_bar navbar-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="http://www.barchef.co"><img src="../assets/bcLogoFinal3.svg" class="barlogo"><img src="../assets/navletters.svg" class="barlogo2"></a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <!-- <li><%= link_to "HOME", root_path %></li> -->
            <!-- <li><a href="#">INBOX</a></li> -->
            <li>
              <%= form_tag '/search/:id', :method => 'get', :class => "navbar-form navbar-right" do  %>
              <div class="form-group input-group">
                <%= text_field_tag :search, params[:search], class:"form-control", placeholder:"Search...Users or Recipes" %>
                <span class="input-group-btn">
                  <button class="btn btn-default">
                    <span class="glyphicon glyphicon-search"></span>
                  </button>
                </span>
              </div>
              <% end %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="/about">ABOUT US</a>
            </li>
            <li>
              <% if user_signed_in? %>
              <%= link_to(destroy_user_session_path, :method => :delete) do %>
              LOGOUT
              <% end %>
            <% else %>
              <%= link_to(new_user_session_path) do %>
              LOGIN
              <% end %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <% if !flash.empty? %>
    <%= flash[:message] %>
    <% end %>
    <%= yield %>

    <!-- <br> -->
    <!-- <footer>
 	<div class="row">
 	<p class="footer-text"><span class="glyphicon glyphicon-copyright-mark"></span> 2016 <a href="https://www.ironhack.com/en">IRONHACK</a></p>
	</div>
</footer> -->
  </body>
</html>

app/views/main/about.html.erb
<div class="container">
	<div class="row">
		<center><h1 class="about">Our Mission</h1></center>
	</div>
	<div class="row row-about">
		<div class="col-sm-6">
			<img src="assets/1.jpg" class="img-thumbnail img-thumbnail-about" alt="Image">
		</div>
		<div class="col-sm-6">
			<div class="well well-inside-about text-center">
				Barchef is here to help chefs, bartenders and the occasional culinary enthusiast share recipes amongst themselves. This social platform allows you to follow users and track the latest restaurant and bar trends.  Keep track of your favorite recipes by liking them and share some of your own.  Sign up today!<p>
				<center><%= link_to "SIGN-UP", new_user_registration_path, class: "btn btn-default btn-home" %></center>
			</div>
		</div>
	</div>
</div>

app/views/main/home.html.erb
<body>
  <div class="container-fluid homepic">
    <div class="row">
      <div class="col-lg-6">
        <div class="barformat">
          <img class="homelogo" src="assets/bcLogoFinal10.svg">
        </div>
      </div>
      <!-- <div class="col-lg-4">
        <div class="barformat">
          <div>
            <img class="chefpic img-thumbnail" src="assets/newchef1.jpg">
          </div>
        </div>
      </div> -->

      <!-- <div class="transbox"></div> -->
      <div class="col-lg-6">
        <div class="barformat">
          <div class="">
            BARCHEF is a social media platform made exclusively for the hospitality industry. Chefs, bartenders &amp kitchen enthusiasts can share recipes amongst themselves. Sign-up today &amp create your own profile to start improving your skills in the
            kitchen or behind the bar!
          </div>
          <div class="">
            <center><%= link_to "SIGN UP", new_user_registration_path, class: "btn btn-default" %></center>
          </div>
        </div>
      </div>

    </div>
  </div>
</body>

app/views/main/signed_in_home.html.erb
<div class="container">
	<div class="row row-main-user-home">
		<div class="col-sm-3">
			<div class="well well-profile well-outer-sign">
		
				<h3>Welcome, <%= current_user.first_name %>!</h3><p>	
				
				<div class="user-home-profile-info text-center">
				<%= link_to (image_tag current_user.avatar.url(:thumb)), user_path(current_user) %>
				<!-- <img src="assets/jose.png" class="img-thumbnail img-user-thumbnail img-main-home-user" alt="Image"> -->
				<ul class="user-home-profile-links">
				<li><strong><%= link_to "MY PROFILE", user_path(current_user) %></strong></li>
				<!-- <li><a href="#">Events</a></li> -->
				</ul>
				</div>
				<div class="row sponsor-box">
				<center><font size="1" color="grey">SPONSOR ADVERTISEMENT</font></center>
				<center><img src="assets/jackdaniels_poster.jpg" alt="Image"></center>
				</div>
			</div>
		</div>
		<div class="col-sm-6">
			<div class="well well-suggested-users well-outer-sign">
				<h2 class="text-center text-suggestions-h1">Suggested Users</h2>
					<div class="row">
		 				<div class="well well-inside well-inside-suggested-users">
		  					<ul class="list-of-suggested-users">
		  						<% @user.each do |one_user| %>
		  						<li>
								<%= image_tag one_user.avatar.url(:thumb) %><p>
		  						<a href="#"> <span class="user-name"><%= link_to "#{one_user.first_name} #{one_user.last_name}", user_path(one_user)%></span></a></li>
	  						<% end %>
		  					</ul>
		  				</div>
					</div>
			</div>
		</div>
		<div class="col-sm-3">	
			<div class="well well-profile well-outer-sign">
				<h3 class="text-center">Following</h3>
					<div class="well well-inside well-inside-following">
						<ul>
						<% @followees.each do |one_followee| %>
					<li> <%=  link_to "#{one_followee.first_name} #{one_followee.last_name}", user_path(one_followee) %> </li>
						
								<% end %>
					    </ul>
			  		</div>
			  		<h3 class="text-center">Cocktail Recipes</h3>
					<div class="well well-inside well-inside-following text-center">
						<ul class="user-home-profile-links">
						<% @recipes.each do |one_recipe| %>
						<li><%= link_to "#{one_recipe.name}", recipe_path(one_recipe) %></li>
						<% end %>
						</ul>
			  		</div>
			</div> 
		</div>
	</div>
</div>

app/views/recipes/_form.html.erb
<%= form_for [@recipe], html: { multipart: true } do |f| %>

	<%= f.label :name %>

	<%= f.text_field :name %>

<br>
	
	<%= f.label :description %>

	<%= f.text_field :description %>
	
<br>

	<%= f.label :instructions %>

	<%= f.text_field :instructions %>

<br>
	<%= f.file_field :avatar %>

	<%= f.button %>
	
<% end %>

app/views/recipes/edit.html.erb
<div class="container">
	<div class="row row-edit-recipe">
		<div class="col-12-sm">
		<h1> Edit Recipe </h1>

			<%= form_for [@recipe], html: { multipart: true } do |f| %>
		
		<br>
			
			<%= f.label :description %>
		<br>
			<%= f.text_field :description %>
	
		<br>

			<%= f.label :instructions %>
		<br>
			<%= f.text_field :instructions %>

		<br>
			<%= f.file_field :avatar %>
		
		<br>

			<%= f.button %>
	
			<% end %>
		</div>
	</div>
</div>

app/views/recipes/new.html.erb
<div class="container">
<div class="row row-new-recipe">
		<div class="col-12-sm">
		<h1> New Recipe </h1> <br>

			<%= form_for [@recipe], html: { multipart: true } do |f| %>
	
			<div class="field">
			<%= f.label :name %>
			<%= f.text_field :name %>
			</div>
		
		
			<div class="field recipe-field">
			<%= f.label :description %>
			<%= f.text_field :description %>
			</div>
	
		
			<div class="field recipe-field">
			<%= f.label :instructions %>
			<%= f.text_field :instructions %>
			</div>

		
			<div class="field">
			<%= f.file_field :avatar %>
			</div>
		

			<%= f.button %>
	
			<% end %>
		</div>
	</div>
</div>

app/views/recipes/show.html.erb
<!-- <div class="well well-inside"> -->
<div class="container"> 
<div class="col-sm-2">
</div>

<div class="col-sm-8">
<div class="well well-recipe">
<div class="well well-inside">
 <ul class="text-center recipe-ul">
	 <li><h1><center><%= @recipe.name %></center></h1></li><br>
	 <li><%= image_tag @recipe.avatar.url(:medium) %></li><br>				
	 
	 <li><strong>Ingredients Description:</strong> <%= @recipe.description %></li>
	 <li><strong>Recipe Instructions:</strong> <%= @recipe.instructions %></li><br>
	 <li><%= link_to "Edit", edit_recipe_path(@recipe) %></li>
	 <li><%= link_to "Delete", recipe_path(@recipe), method: "delete" %></li>	 
 </ul> 
</div>
</div>
</div>

<div class="col-sm-2">
</div>
</div>
 <!-- </div> -->

app/views/search/index.html.erb
	<div class="row text-center">
		<h1>Search Results</h1>
	</div>
	<div class="row">
		<div class="container">
		<div class="col-6-sm text-center">
		<% @user.each do |one_user| %>	
			User Search Result: <%= link_to "#{one_user.first_name} #{one_user.last_name}", user_path(one_user)%>
		<% end %>
		</div>
		<div class="col-6-sm text-center">
		<% @recipe.each do |one_recipe| %>
			Recipe Result: <%= link_to "#{one_recipe.name}", recipe_path(one_recipe)%>
		<% end %>
		</div>
		</div>
	</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row row-profile-main">
		<div class="col-sm-4">
			<div class="well well-main-profile">
				<div class="well well-inside text-center ">
					<ul class="well-left-profile">
						<li><%= image_tag @user.avatar.url(:thumb) %></li>
							<li><h3><%= @user.first_name %> <%= @user.last_name %></h3></li>
										<% if @user == current_user %>
							<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
							<li><%= link_to "Add New Recipe", new_recipe_path %></li>
												<% end %>
                            			<br><li>Following: <%= @user.followees_count %></li>
                            			<li>Followers: <%= @user.followers_count %></li>
                            			<% if current_user.follows?(@user) %>
                            <li> <%= link_to "Unfollow", "/unfollow/#{@user.id}", method: :post, class: "btn btn-default btn-follow " %>
											<% else %>
							<li> <%= link_to "Follow", "/follow/#{@user.id}", method: :post, class: "btn btn-default btn-follow " %>
                                              </li>
                            			<% end %>

					 </ul>
				    </div>
				

				<div class="well well-inside text-center">
				<ul class="well-left-profile">
					<li><strong>USER INFORMATION</strong></li><br>
					<li>Location: <%= @user.location %></li>
					<li>Position: <%= @user.bio %></li>
					<li>Industry: <%= @user.industry %></li>
					<li>Company: <%= @user.company %></li>
							
				</ul>
				</div>
			
                <div class="well well-inside text-center">
                <ul class="well-left-profile">
                	<li><strong>FOLLOWING</strong></li><br>
                	<% @followees.each do |one_followee| %>
					<li> <%=  link_to "#{one_followee.first_name} #{one_followee.last_name}", user_path(one_followee) %> </li>
						
								<% end %>
                </ul>
                </div>
                <div class="well well-inside text-center">
                <ul class="well-left-profile">
                	<li><strong>LIKED RECIPES</strong></li><br>
                	<% @liked_recipes.each do |one_liked_recipe| %>
					<li> <%=  link_to "#{one_liked_recipe.name}", recipe_path(one_liked_recipe) %> </li>
						
								<% end %>
                </ul>
                </div>
			</div>
		</div>
		<div class="col-sm-8 col-profile-main">
			<% @recipes.each do |one_recipe| %>
			<div class="well well-main-profile well-main-profile-2">
				<div class="well well-inside">
				<ul class="text-center recipe-ul">			
				<li><%= image_tag one_recipe.avatar.url(:medium), class: "img-thumbnail img-recipe" %></li>
					<li><h4>Recipe: <%= link_to "#{one_recipe.name}", recipe_path(one_recipe) %></h4></li>
					
					<li><strong>Ingredients:</strong> <%= one_recipe.description %></li>
					<li><strong>Instructions:</strong> <%= one_recipe.instructions %></li><br>
							<% if @user == current_user %>
					<li><%= link_to "Edit", edit_recipe_path(one_recipe)  %></li>
					<li><%= link_to "Delete", recipe_path(one_recipe), method: "delete" %></li>
							<% end %>
							<% if current_user.likes?(one_recipe) %>
					<li> <%= link_to "Unlike", "/unlike/#{one_recipe.id}", method: :post, class: "btn btn-default btn-follow " %>
                                              </li><br>
                                              <% else %>
                    <li> <%= link_to "Like", "/like/#{one_recipe.id}", method: :post, class: "btn btn-default btn-follow " %>
                                              </li><br>
                    		<% end %>
                    		<li>Likes: <%= one_recipe.likers_count %></li>
				</ul>
				</div>
			</div>
			<% end %>
		</div>
	</div>
</div>